### ISSUE TITLE
Forgot Password / Reset Password feature

### ISSUE THREAD

**Issue by SteveGlancey** [uncommonjoe/Abide#9]
In the event that someone has forgotten their password, we need a text link to initiate a forgot password sequence on the log in screen. 

Text link under login button: "Forgot Password?"
Opens email field option: "Email" + "Reset Password" button after typing in their email. 
Check database to confirm a matching email is associated with a user. 
If no user is found, return message: "No such user exists with that email". Allow the user to try again on the same screen. 
If there is a user with that email in the database, send an email where the user can click the link and type in a new password in a field. Make the password visible as its typed in. This isn't bank records so we don't have to be overly cautious.

**Comment by uncommonjoe** [comment]
I think along with this, I should look into email authentication with account creation.

**Comment by uncommonjoe** [comment]
I was unable to create email authentication upon account creation as it's not built in to Firebase. 

Note: After clicking the link in the email to reset password, all that is handled by Firebase and I don't have control over the password input type or UI there.
